/**
*   Test class for class ClsRest4Heroku.
*
@author Di Chen
@created 2013-05-29
@version 1.0
@since 20.0
*
@changelog
* 2013-05-29 Di Chen <di.chen@itbconsult.com>
* - Created
*- Test coverage 100%
*/
@isTest
private class IMP_BI_ClsRest4Heroku_Test {

    static testMethod void testCls() {
        Test.startTest();
        
        IMP_BI_ClsRest4Heroku cls = new IMP_BI_ClsRest4Heroku();
        
        system.assert(true);
        Test.stopTest();
    }
}